<?php

namespace Database\Seeders;

use App\Models\MockTestQuestion;
use Illuminate\Database\Seeder;

class MockTestQuestionSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate or refresh to avoid duplicates when re-seeding
        MockTestQuestion::truncate();

        $questions = [
            // ================= ROAD SIGNS =================
            [
                'category' => 'Road Signs',
                'question' => 'What does an eight-sided (octagonal) red road sign indicate?',
                'option_a' => 'Yield the right of way',
                'option_b' => 'Come to a complete stop',
                'option_c' => 'Do not enter the roadway',
                'option_d' => 'Wrong way traffic',
                'correct_option' => 'B',
                'explanation' => 'A red octagonal sign always means STOP. You must come to a complete stop at the stop line, crosswalk, or intersection before proceeding safely.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'A yellow diamond-shaped road sign with black symbols represents:',
                'option_a' => 'A mandatory direction order',
                'option_b' => 'A warning of hazards or changing road conditions ahead',
                'option_c' => 'A highway speed limit regulation',
                'option_d' => 'A tourist attraction direction',
                'correct_option' => 'B',
                'explanation' => 'Diamond-shaped yellow signs alert drivers to potential dangers, upcoming road changes, or hazards ahead (such as sharp curves, merge lanes, or pedestrian zones).',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'What does a circular sign with a red border containing the number "50" mean?',
                'option_a' => 'Recommended speed is 50 km/h',
                'option_b' => 'Minimum allowable speed is 50 km/h',
                'option_c' => 'Maximum legal speed limit is 50 km/h',
                'option_d' => 'Distance to next exit is 50 km',
                'correct_option' => 'C',
                'explanation' => 'Red circular signs enforce legal prohibitions or mandatory limits. A number inside a red ring dictates the maximum legal speed limit.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'An inverted triangular sign (apex pointing downwards) with a red border means:',
                'option_a' => 'Stop and wait for light',
                'option_b' => 'Yield / Give way to traffic on the main road',
                'option_c' => 'No overtaking allowed',
                'option_d' => 'End of priority road',
                'correct_option' => 'B',
                'explanation' => 'The upside-down triangle is universally used for Yield / Give Way. Drivers must slow down and give priority to oncoming or main road traffic.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'What does a red circle with a horizontal white bar across the center indicate?',
                'option_a' => 'No Entry for all motor vehicles',
                'option_b' => 'Road closed for maintenance',
                'option_c' => 'Stop for customs inspection',
                'option_d' => 'One-way street ahead',
                'correct_option' => 'A',
                'explanation' => 'The red disk with a horizontal white bar prohibits entry to all vehicles from that direction into a street or highway.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'A blue rectangular sign with a white capital letter "P" signifies:',
                'option_a' => 'Police station ahead',
                'option_b' => 'Designated parking zone',
                'option_c' => 'Pedestrian crossing only',
                'option_d' => 'Petrol station distance',
                'correct_option' => 'B',
                'explanation' => 'Blue rectangular signs provide useful facility information. A white "P" on a blue background denotes an authorized parking facility or area.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'A blue circular sign with a white arrow pointing to the right indicates:',
                'option_a' => 'Right turn is prohibited',
                'option_b' => 'Mandatory direction - Turn right ahead',
                'option_c' => 'Optional right turn lane',
                'option_d' => 'One-way traffic coming from the right',
                'correct_option' => 'B',
                'explanation' => 'Blue circular signs convey mandatory instructions. A white arrow inside a blue circle dictates the required direction you must follow.',
            ],

            // ================= TRAFFIC RULES =================
            [
                'category' => 'Traffic Rules',
                'question' => 'When approaching a multi-lane roundabout, which vehicles have the right of way?',
                'option_a' => 'Vehicles accelerating to enter the roundabout',
                'option_b' => 'Vehicles already circulating inside the roundabout',
                'option_c' => 'The largest commercial vehicle approaching',
                'option_d' => 'Vehicles approaching from your left side',
                'correct_option' => 'B',
                'explanation' => 'Traffic already inside the roundabout has right-of-way over entering traffic unless traffic lights or signs specify otherwise.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'What is the standard procedure when an emergency vehicle with active flashing lights and siren approaches from behind?',
                'option_a' => 'Accelerate quickly to stay ahead of the emergency vehicle',
                'option_b' => 'Maintain your current speed and stay in the middle lane',
                'option_c' => 'Safely pull over to the nearest road edge and come to a complete stop',
                'option_d' => 'Turn on your hazard lights and stop immediately in your current lane',
                'correct_option' => 'C',
                'explanation' => 'Always safely signal, pull over to the side of the road, clear the lane, and stop to give emergency response vehicles immediate right-of-way.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'Under what circumstances may a driver legally park in front of a private driveway?',
                'option_a' => 'Only if leaving hazard warning lights on',
                'option_b' => 'If stopping for less than 5 minutes',
                'option_c' => 'Never, unless directed by a police officer or emergency official',
                'option_d' => 'Only during nighttime hours',
                'correct_option' => 'C',
                'explanation' => 'Parking in front of public or private driveways is strictly prohibited by traffic law because it obstructs vehicle ingress and egress.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'What does a solid double white line down the center of a two-way roadway indicate?',
                'option_a' => 'Overtaking is permitted if the road is clear',
                'option_b' => 'Lane changing and overtaking across the lines is strictly forbidden for both directions',
                'option_c' => 'Reversible lane boundary',
                'option_d' => 'Pedestrian crossing zone ahead',
                'correct_option' => 'B',
                'explanation' => 'Double solid white or yellow central lines prohibit vehicles on either side from crossing to pass or overtake other vehicles.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'What is the purpose of the "Two-Second Rule" in driving?',
                'option_a' => 'The time allowed to pause at a stop sign',
                'option_b' => 'The minimum safe following distance behind a vehicle under normal dry road conditions',
                'option_c' => 'The maximum duration allowed for changing lanes',
                'option_d' => 'The response time delay allowed for traffic lights',
                'correct_option' => 'B',
                'explanation' => 'The 2-second rule helps drivers maintain a safe buffer distance behind the vehicle in front, giving adequate reaction time to prevent rear-end collisions.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'When are you allowed to overtake another vehicle near a marked pedestrian zebra crossing?',
                'option_a' => 'If the pedestrian is walking away from your lane',
                'option_b' => 'During daylight hours only',
                'option_c' => 'Never overtake the lead vehicle stopping at or approaching a zebra crossing',
                'option_d' => 'If you flash your headlights first',
                'correct_option' => 'C',
                'explanation' => 'Passing a vehicle that has slowed down or stopped at a pedestrian crossing is extremely dangerous and illegal, as pedestrians may be crossing unseen.',
            ],

            // ================= VEHICLE CONTROLS =================
            [
                'category' => 'Vehicle Controls',
                'question' => 'What is the primary safety function of an Anti-lock Braking System (ABS)?',
                'option_a' => 'To reduce brake pedal pressure required by the driver',
                'option_b' => 'To prevent wheel lockup under panic braking, preserving steering control',
                'option_c' => 'To automatically brake the car when tailgating',
                'option_d' => 'To eliminate brake shoe and pad wear',
                'correct_option' => 'B',
                'explanation' => 'ABS rapidly pumps the brakes during heavy emergency stops to stop wheels from locking, allowing the driver to steer around obstacles.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'Which headlights setting should be used when driving through thick fog or heavy snowfall during the night?',
                'option_a' => 'High beam headlights',
                'option_b' => 'Low beam headlights (and front/rear fog lights if equipped)',
                'option_c' => 'Parking lights only',
                'option_d' => 'Hazard warning lights while driving at full speed',
                'correct_option' => 'B',
                'explanation' => 'High beams reflect off water droplets in fog/snow directly back into the driver eyes (glare). Low beams aim lower on the road surface.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'In a manual transmission car, what function does the clutch pedal perform?',
                'option_a' => 'Increases engine oil pressure',
                'option_b' => 'Disengages the engine flywheel from the transmission to allow smooth gear shifting',
                'option_c' => 'Locks the rear differential during cornering',
                'option_d' => 'Applies secondary emergency rear brakes',
                'correct_option' => 'B',
                'explanation' => 'Depressing the clutch disconnects engine power output from the gearbox, enabling gear ratio changes without grinding gears.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'If the temperature gauge on your dashboard spikes into the red zone while driving, what should you do first?',
                'option_a' => 'Increase speed to get air flowing faster through the radiator',
                'option_b' => 'Turn on full air conditioning to cool the engine bay',
                'option_c' => 'Safely pull off the road, turn off the engine, and allow it to cool before checking coolant levels',
                'option_d' => 'Immediately open the hot radiator cap with your bare hands',
                'correct_option' => 'C',
                'explanation' => 'Overheating can ruin an engine. Pulling over safely and letting it cool prevents severe engine failure. Never remove hot radiator caps under pressure.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'What is the recommended hand placement position on the steering wheel for optimal control and airbag deployment safety?',
                'option_a' => '12 o\'clock with one hand at the top',
                'option_b' => '9 o\'clock and 3 o\'clock (or 10 and 2)',
                'option_c' => 'Both hands resting on the bottom at 6 o\'clock',
                'option_d' => 'Crossed arms across the center hub',
                'correct_option' => 'B',
                'explanation' => 'The 9 and 3 o\'clock position provides maximum leverage, smooth wheel turning, and keeps arms clear of deploying steering wheel airbags.',
            ],

            // ================= EMERGENCIES =================
            [
                'category' => 'Emergencies',
                'question' => 'What should a driver do if their vehicle begins to hydroplane (glide on top of standing water)?',
                'option_a' => 'Slam hard on the brake pedal immediately',
                'option_b' => 'Smoothly ease off the accelerator, hold steering wheel firm, and refrain from sudden braking or turning',
                'option_c' => 'Turn the steering wheel sharply towards the shoulder',
                'option_d' => 'Shift into neutral and apply the handbrake',
                'correct_option' => 'B',
                'explanation' => 'Sudden braking or sharp steering while hydroplaning causes uncontrollable skidding. Easing off the gas lets tires regain contact with asphalt.',
            ],
            [
                'category' => 'Emergencies',
                'question' => 'If a tire unexpectedly blows out while traveling at high highway speeds, your immediate action should be:',
                'option_a' => 'Stomp on the brakes to stop as fast as possible',
                'option_b' => 'Grip steering wheel firmly with both hands, maintain directional control, ease off gas, and glide safely off the road',
                'option_c' => 'Turn off the ignition switch immediately',
                'option_d' => 'Jerk the steering wheel sharply in the opposite direction of the pull',
                'correct_option' => 'B',
                'explanation' => 'Braking hard during a blowout can flip or spin the car. Keeping steering firm and decelerating gradually prevents loss of control.',
            ],
            [
                'category' => 'Emergencies',
                'question' => 'If your foot brake pedal completely fails while driving downhill, how should you attempt to slow the vehicle?',
                'option_a' => 'Turn off the ignition key to lock the steering',
                'option_b' => 'Downshift to lower gears sequentially and carefully pull up the parking brake while holding the release button',
                'option_c' => 'Shift immediately into Reverse gear',
                'option_d' => 'Jump out of the moving vehicle',
                'correct_option' => 'B',
                'explanation' => 'Engine braking (downshifting) reduces speed naturally, and gradual application of the emergency handbrake can bring the car to a controlled stop.',
            ],
            [
                'category' => 'Emergencies',
                'question' => 'How does driving on wet or icy pavement affect a vehicle\'s total stopping distance?',
                'option_a' => 'It reduces stopping distance by half',
                'option_b' => 'It has no measurable effect if tires are brand new',
                'option_c' => 'It increases stopping distance by 2 to 10 times compared to dry roads',
                'option_d' => 'It affects steering only, not braking distance',
                'correct_option' => 'C',
                'explanation' => 'Slippery surfaces drastically diminish tire traction, multiplying stopping distance required up to 10x in icy conditions.',
            ],

            // ================= GENERAL KNOWLEDGE =================
            [
                'category' => 'General',
                'question' => 'What is a vehicle\'s "blind spot"?',
                'option_a' => 'The area directly illuminated by high beam headlights',
                'option_b' => 'The ground area directly under the front bumper',
                'option_c' => 'Areas around the vehicle that cannot be seen in side or rear-view mirrors',
                'option_d' => 'The window tinted area on rear passenger doors',
                'correct_option' => 'C',
                'explanation' => 'Blind spots are zones outside mirror coverage. Drivers must perform over-the-shoulder head checks before changing lanes or turning.',
            ],
            [
                'category' => 'General',
                'question' => 'What essential checks should be performed before embarking on a long highway trip?',
                'option_a' => 'Tire pressure & tread depth, engine oil/coolant levels, brake fluid, and lighting equipment',
                'option_b' => 'Washing the car exterior and checking audio speakers',
                'option_c' => 'Checking fuel tank level only',
                'option_d' => 'Replacing all spark plugs regardless of age',
                'correct_option' => 'A',
                'explanation' => 'Routine preventive checks on tires, fluids, lights, and wipers ensure vehicle roadworthiness and prevent breakdowns.',
            ],
            [
                'category' => 'General',
                'question' => 'What is the safest remedy if you experience drowsiness or severe fatigue while driving on a long road trip?',
                'option_a' => 'Turn up the radio volume and open all windows',
                'option_b' => 'Drink caffeinated beverages while continuing to drive without stopping',
                'option_c' => 'Safely pull off at a rest stop or service plaza to take a nap or rest',
                'option_d' => 'Speed up to reach your destination faster',
                'correct_option' => 'C',
                'explanation' => 'Driver fatigue impairs reaction time as severely as alcohol. The only effective cure for sleepiness is taking a rest break or nap.',
            ],
            [
                'category' => 'General',
                'question' => 'Under traffic safety laws, when is it acceptable to hold a mobile phone in your hand to text while driving?',
                'option_a' => 'When stopped at a red traffic signal',
                'option_b' => 'When driving below 20 km/h in light traffic',
                'option_c' => 'Never while operating a vehicle on public roads',
                'option_d' => 'If using your non-dominant hand',
                'correct_option' => 'C',
                'explanation' => 'Handheld phone use (texting or holding) while driving is illegal on public roads because it causes cognitive, visual, and manual distractions.',
            ],
            // ================= ADDITIONAL QUESTIONS =================
            [
                'category' => 'General',
                'question' => 'When parallel parking on a hill facing downwards, which way should you turn your steering wheel?',
                'option_a' => 'Towards the curb (right)',
                'option_b' => 'Away from the curb (left)',
                'option_c' => 'Keep the wheels perfectly straight',
                'option_d' => 'It does not matter if the handbrake is on',
                'correct_option' => 'A',
                'explanation' => 'When parking facing downhill, turn your wheels toward the curb so that if the brakes fail, the vehicle rolls into the curb rather than into the flow of traffic.',
            ],
            [
                'category' => 'General',
                'question' => 'What is the purpose of the head restraint on your seat?',
                'option_a' => 'To make long journeys more comfortable',
                'option_b' => 'To help prevent whiplash neck injuries in the event of a rear-end collision',
                'option_c' => 'To stop the driver from falling asleep',
                'option_d' => 'To improve posture while driving',
                'correct_option' => 'B',
                'explanation' => 'A properly adjusted head restraint reduces the backward movement of the head in a rear-end collision, decreasing the risk of neck injury (whiplash).',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'What does a solid yellow line on your side of the center line mean?',
                'option_a' => 'You may pass if the road is clear',
                'option_b' => 'Do not pass',
                'option_c' => 'Speed limit is reduced ahead',
                'option_d' => 'Approaching a Stop sign',
                'correct_option' => 'B',
                'explanation' => 'A solid yellow line on your side of the road means passing is prohibited.',
            ],
            [
                'category' => 'Road Signs',
                'question' => 'A sign with a red circle and a red diagonal line through a black arrow turning left means:',
                'option_a' => 'Do not turn right',
                'option_b' => 'Do not turn left',
                'option_c' => 'No U-turn allowed',
                'option_d' => 'Left turn gives way',
                'correct_option' => 'B',
                'explanation' => 'The red prohibition circle with a stroke through a left-pointing arrow indicates that making a left turn is prohibited.',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'Who has the right-of-way at an uncontrolled intersection across equal roads?',
                'option_a' => 'The vehicle traveling fastest',
                'option_b' => 'The vehicle turning right',
                'option_c' => 'The vehicle approaching from the right',
                'option_d' => 'The vehicle approaching from the left',
                'correct_option' => 'C',
                'explanation' => 'At an uncontrolled intersection, you must yield to vehicles approaching from your right (right-before-left rule).',
            ],
            [
                'category' => 'Traffic Rules',
                'question' => 'When are you allowed to use your vehicle\'s horn?',
                'option_a' => 'To greet friends on the sidewalk',
                'option_b' => 'To express frustration at slow drivers',
                'option_c' => 'To warn other road users of impending danger',
                'option_d' => 'To alert someone inside a house that you are waiting outside',
                'correct_option' => 'C',
                'explanation' => 'The horn should only be used to warn others of danger or to let them know you are there to prevent an accident.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'When should you check your engine oil level?',
                'option_a' => 'While the engine is running and hot',
                'option_b' => 'When the engine is cold and the car is parked on level ground',
                'option_c' => 'Only when the oil warning light comes on',
                'option_d' => 'Immediately after a long journey on an incline',
                'correct_option' => 'B',
                'explanation' => 'For an accurate reading, the vehicle should be on level ground with a cold engine so all the oil has drained back into the sump.',
            ],
            [
                'category' => 'Vehicle Controls',
                'question' => 'What happens when your tires are under-inflated?',
                'option_a' => 'Fuel consumption decreases',
                'option_b' => 'Steering becomes much lighter and easier',
                'option_c' => 'The vehicle uses more fuel and tire grips reduce',
                'option_d' => 'The tires will last considerably longer',
                'correct_option' => 'C',
                'explanation' => 'Under-inflated tires increase rolling resistance (using more fuel), reduce grip, run hotter, and wear out along the outer edges prematurely.',
            ],
            [
                'category' => 'Emergencies',
                'question' => 'If your engine stalls while you are driving in traffic, what should you do?',
                'option_a' => 'Slam the brakes immediately and leave the vehicle',
                'option_b' => 'Turn on your hazard lights, brake gently, and steer to the side of the road',
                'option_c' => 'Start waving your arms out the window',
                'option_d' => 'Put the car into Reverse gear to try bump-starting it',
                'correct_option' => 'B',
                'explanation' => 'Warn other drivers using hazard lights and try to maintain enough momentum to coast to a safe place off the road.',
            ],
            [
                'category' => 'Emergencies',
                'question' => 'What is the first step you should take if you are involved in a collision?',
                'option_a' => 'Drive away quickly if there is no major damage',
                'option_b' => 'Stop your vehicle safely and turn on your hazard warning lights',
                'option_c' => 'Start taking pictures before checking on anyone',
                'option_d' => 'Admit fault immediately to the other party',
                'correct_option' => 'B',
                'explanation' => 'You must stop safely, secure the scene with hazard lights to prevent further accidents, and check for injuries before continuing.',
            ],
        ];

        foreach ($questions as $q) {
            MockTestQuestion::create($q);
        }
    }
}
